package net.cmd.resourcepack;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonObject;
import net.cmd.compat.CMDModelCase;
import net.cmd.merge.CMDBuildResult;
import net.cmd.merge.CMDItemDefinitionMerger;
import net.cmd.util.ZipUtils;

import java.io.File;
import java.io.FileWriter;
import java.nio.file.Files;
import java.util.List;
import java.util.Map;

/**
 * Builds the final merged resources.zip for CMD.
 */
public class CMDResourcePackBuilder {

    private static final Gson GSON = new GsonBuilder().setPrettyPrinting().disableHtmlEscaping().create();

    public CMDBuildResult build(File worldFolder, Map<String, List<CMDModelCase>> itemCases, List<String> sourceIds) {
        CMDBuildResult result = new CMDBuildResult();
        try {
            ResourcePackBackupManager backupManager = new ResourcePackBackupManager();
            backupManager.backup(worldFolder);

            File workDir = createWorkDirectory(worldFolder);
            PackStructureBuilder structureBuilder = new PackStructureBuilder();
            structureBuilder.createWorkTree(workDir);

            writePackMeta(workDir);
            result.writtenItemFiles = writeMergedItemDefinitions(workDir, itemCases);
            writeLangFile(workDir, itemCases);
            writeSourcesFile(workDir, itemCases, sourceIds);

            File outputZip = new File(worldFolder, "resources.zip");
            ZipUtils.zipFolder(workDir, outputZip);
            deleteRecursively(workDir);

            result.success = true;
            result.outputZipPath = outputZip.getAbsolutePath();
            result.message = "resources.zip built successfully";
            System.out.println("[CMD] Built resources.zip successfully");
        } catch (Exception e) {
            e.printStackTrace();
            result.success = false;
            result.message = "Failed building resources.zip";
            System.out.println("[CMD] Failed building resources.zip");
        }
        return result;
    }

    private File createWorkDirectory(File worldFolder) throws Exception {
        File workDir = new File(worldFolder, "cmd_build_tmp");
        if (workDir.exists()) deleteRecursively(workDir);
        Files.createDirectories(workDir.toPath());
        return workDir;
    }

    private void writePackMeta(File workDir) throws Exception {
        JsonObject pack = new JsonObject();
        pack.addProperty("pack_format", 71);
        pack.addProperty("description", "Generated by CMD");
        JsonObject root = new JsonObject();
        root.add("pack", pack);
        try (FileWriter writer = new FileWriter(new File(workDir, "pack.mcmeta"))) { GSON.toJson(root, writer); }
    }

    private int writeMergedItemDefinitions(File workDir, Map<String, List<CMDModelCase>> itemCases) throws Exception {
        File itemsDir = new File(workDir, "assets/minecraft/items");
        Files.createDirectories(itemsDir.toPath());
        int count = 0;
        for (Map.Entry<String, List<CMDModelCase>> entry : itemCases.entrySet()) {
            JsonObject merged = CMDItemDefinitionMerger.merge(entry.getKey(), entry.getValue());
            try (FileWriter writer = new FileWriter(new File(itemsDir, entry.getKey() + ".json"))) { GSON.toJson(merged, writer); }
            count++;
        }
        return count;
    }

    private void writeLangFile(File workDir, Map<String, List<CMDModelCase>> itemCases) throws Exception {
        File langDir = new File(workDir, "assets/cmd/lang");
        Files.createDirectories(langDir.toPath());
        CMDLangGenerator langGenerator = new CMDLangGenerator();
        JsonObject lang = langGenerator.generate(itemCases);
        try (FileWriter writer = new FileWriter(new File(langDir, "en_us.json"))) { GSON.toJson(lang, writer); }
    }

    private void writeSourcesFile(File workDir, Map<String, List<CMDModelCase>> itemCases, List<String> sourceIds) throws Exception {
        StringBuilder sb = new StringBuilder();
        sb.append("CMD merged sources

");
        sb.append("Sources:
");
        for (String sourceId : sourceIds) sb.append("- ").append(sourceId).append("
");
        sb.append("
Definitions by item:
");
        for (Map.Entry<String, List<CMDModelCase>> entry : itemCases.entrySet()) {
            sb.append("
[").append(entry.getKey()).append("]
");
            for (CMDModelCase modelCase : CMDItemDefinitionMerger.normalizeUniqueCases(entry.getValue())) {
                sb.append("- ").append(modelCase.modelId).append(" -> ").append(modelCase.modelPath).append("
");
            }
        }
        Files.writeString(new File(workDir, "SOURCES.txt").toPath(), sb.toString());
    }

    private void deleteRecursively(File file) {
        if (!file.exists()) return;
        if (file.isDirectory()) {
            File[] children = file.listFiles();
            if (children != null) for (File child : children) deleteRecursively(child);
        }
        file.delete();
    }
}
